name: html_previewer_app
description: "Flutter application designed for previewing HTML content."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # Provider
  provider: ^6.1.5

  # UI
  flutter_html: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true